# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/veysiadn/ecat_userspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/veysiadn/ecat_userspace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/veysiadn/ecat_userspace/CMakeFiles /home/veysiadn/ecat_userspace/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/veysiadn/ecat_userspace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ecat_node

# Build rule for target.
ecat_node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ecat_node
.PHONY : ecat_node

# fast build rule for target.
ecat_node/fast:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/build
.PHONY : ecat_node/fast

src/ecat_lifecycle.o: src/ecat_lifecycle.cpp.o

.PHONY : src/ecat_lifecycle.o

# target to build an object file
src/ecat_lifecycle.cpp.o:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/ecat_lifecycle.cpp.o
.PHONY : src/ecat_lifecycle.cpp.o

src/ecat_lifecycle.i: src/ecat_lifecycle.cpp.i

.PHONY : src/ecat_lifecycle.i

# target to preprocess a source file
src/ecat_lifecycle.cpp.i:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/ecat_lifecycle.cpp.i
.PHONY : src/ecat_lifecycle.cpp.i

src/ecat_lifecycle.s: src/ecat_lifecycle.cpp.s

.PHONY : src/ecat_lifecycle.s

# target to generate assembly for a file
src/ecat_lifecycle.cpp.s:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/ecat_lifecycle.cpp.s
.PHONY : src/ecat_lifecycle.cpp.s

src/ecat_node.o: src/ecat_node.cpp.o

.PHONY : src/ecat_node.o

# target to build an object file
src/ecat_node.cpp.o:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/ecat_node.cpp.o
.PHONY : src/ecat_node.cpp.o

src/ecat_node.i: src/ecat_node.cpp.i

.PHONY : src/ecat_node.i

# target to preprocess a source file
src/ecat_node.cpp.i:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/ecat_node.cpp.i
.PHONY : src/ecat_node.cpp.i

src/ecat_node.s: src/ecat_node.cpp.s

.PHONY : src/ecat_node.s

# target to generate assembly for a file
src/ecat_node.cpp.s:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/ecat_node.cpp.s
.PHONY : src/ecat_node.cpp.s

src/ecat_slave.o: src/ecat_slave.cpp.o

.PHONY : src/ecat_slave.o

# target to build an object file
src/ecat_slave.cpp.o:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/ecat_slave.cpp.o
.PHONY : src/ecat_slave.cpp.o

src/ecat_slave.i: src/ecat_slave.cpp.i

.PHONY : src/ecat_slave.i

# target to preprocess a source file
src/ecat_slave.cpp.i:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/ecat_slave.cpp.i
.PHONY : src/ecat_slave.cpp.i

src/ecat_slave.s: src/ecat_slave.cpp.s

.PHONY : src/ecat_slave.s

# target to generate assembly for a file
src/ecat_slave.cpp.s:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/ecat_slave.cpp.s
.PHONY : src/ecat_slave.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/timing.o: src/timing.cpp.o

.PHONY : src/timing.o

# target to build an object file
src/timing.cpp.o:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/timing.cpp.o
.PHONY : src/timing.cpp.o

src/timing.i: src/timing.cpp.i

.PHONY : src/timing.i

# target to preprocess a source file
src/timing.cpp.i:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/timing.cpp.i
.PHONY : src/timing.cpp.i

src/timing.s: src/timing.cpp.s

.PHONY : src/timing.s

# target to generate assembly for a file
src/timing.cpp.s:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/timing.cpp.s
.PHONY : src/timing.cpp.s

src/xboxController.o: src/xboxController.cpp.o

.PHONY : src/xboxController.o

# target to build an object file
src/xboxController.cpp.o:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/xboxController.cpp.o
.PHONY : src/xboxController.cpp.o

src/xboxController.i: src/xboxController.cpp.i

.PHONY : src/xboxController.i

# target to preprocess a source file
src/xboxController.cpp.i:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/xboxController.cpp.i
.PHONY : src/xboxController.cpp.i

src/xboxController.s: src/xboxController.cpp.s

.PHONY : src/xboxController.s

# target to generate assembly for a file
src/xboxController.cpp.s:
	$(MAKE) -f CMakeFiles/ecat_node.dir/build.make CMakeFiles/ecat_node.dir/src/xboxController.cpp.s
.PHONY : src/xboxController.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ecat_node"
	@echo "... src/ecat_lifecycle.o"
	@echo "... src/ecat_lifecycle.i"
	@echo "... src/ecat_lifecycle.s"
	@echo "... src/ecat_node.o"
	@echo "... src/ecat_node.i"
	@echo "... src/ecat_node.s"
	@echo "... src/ecat_slave.o"
	@echo "... src/ecat_slave.i"
	@echo "... src/ecat_slave.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/timing.o"
	@echo "... src/timing.i"
	@echo "... src/timing.s"
	@echo "... src/xboxController.o"
	@echo "... src/xboxController.i"
	@echo "... src/xboxController.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

